### ISSUE TITLE
if select yarn yes return error

### ISSUE THREAD

**Issue by ilviandante77** [thundernet8/generator-mpvue-project#1]
question:license: (MIT)
 question:use typescript(Y/n): (Y)
 question:use yarn(Y/n): (Y)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command failed: cd prova && yarn
/bin/sh: yarn: command not found

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)

**Comment by thundernet8** [comment]
you should install yarn first. [Install Yarn](https://yarnpkg.com/lang/en/docs/install/)

And else this is a generator for generating boilerplate project of miniprogram which only popular in China, you have the wrong choice maybe.
