### ISSUE TITLE
运行 npm run dev 报错

### ISSUE THREAD

**Issue by liuyatao** [thundernet8/generator-mpvue-project#2]
module.js:545
    throw err;
    ^

Error: Cannot find module '../.dll/manifest.json'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liuyatao/code/mpvue/test/test/build/webpack.base.conf.js:167:23)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/liuyatao/code/mpvue/test/test/build/webpack.dev.conf.js:5:25)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liuyatao/.npm/_logs/2018-04-21T08_25_36_014Z-debug.log

**Comment by thundernet8** [comment]
npm run dll先


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： 刘亚涛 <notifications@github.com> 日期: 2018/4/21  16:27  (GMT+08:00) 收件人： thundernet8/generator-mpvue-project <generator-mpvue-project@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [thundernet8/generator-mpvue-project] 运行 npm run dev 报错 (#2) 
module.js:545

throw err;

^
Error: Cannot find module '../.dll/manifest.json'

at Function.Module._resolveFilename (module.js:543:15)

at Function.Module._load (module.js:470:25)

at Module.require (module.js:593:17)

at require (internal/module.js:11:18)

at Object. (/Users/liuyatao/code/mpvue/test/test/build/webpack.base.conf.js:167:23)

at Module._compile (module.js:649:30)

at Object.Module._extensions..js (module.js:660:10)

at Module.load (module.js:561:32)

at tryModuleLoad (module.js:501:12)

at Function.Module._load (module.js:493:3)

at Module.require (module.js:593:17)

at require (internal/module.js:11:18)

at Object. (/Users/liuyatao/code/mpvue/test/test/build/webpack.dev.conf.js:5:25)

at Module._compile (module.js:649:30)

at Object.Module._extensions..js (module.js:660:10)

at Module.load (module.js:561:32)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! test@1.0.0 dev: node build/dev-server.js

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the test@1.0.0 dev script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/liuyatao/.npm/_logs/2018-04-21T08_25_36_014Z-debug.log

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thundernet8/generator-mpvue-project","title":"thundernet8/generator-mpvue-project","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thundernet8/generator-mpvue-project"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"运行 npm run dev 报错 (#2)"}],"action":{"name":"View Issue","url":"https://github.com/thundernet8/generator-mpvue-project/issues/2"}}}
