### ISSUE TITLE
根本运行不起来呀...

### ISSUE THREAD

**Issue by zacksleo** [thundernet8/generator-mpvue-project#3]
根据 #2 ，首先运行了 `npm run dll`, 然后出现以下错误

```
> node build/dev-server.js

/Users/zacksleo/projects/test/build/dev-server.js:34
    if (fs.existsSync(dllPath)) {
    ^

ReferenceError: fs is not defined
    at dll (/Users/zacksleo/projects/test/build/dev-server.js:34:5)
    at Object.<anonymous> (/Users/zacksleo/projects/test/build/dev-server.js:173:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zacksleo/.npm/_logs/2018-05-06T15_36_41_703Z-debug.log

```

然后我在`dev-server.js`中加上了 `var fs = require('fs');` , 出现以下错误

```
> node build/dev-server.js

(node:32939) UnhandledPromiseRejectionWarning: ReferenceError: dllWebpackConfig is not defined
    at Promise (/Users/zacksleo/projects/test/build/dev-server.js:46:17)
    at new Promise (<anonymous>)
    at dll (/Users/zacksleo/projects/test/build/dev-server.js:45:12)
    at Object.<anonymous> (/Users/zacksleo/projects/test/build/dev-server.js:174:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:32939) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32939) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by thundernet8** [comment]
@zacksleo 重新安装一遍试试

**Comment by zacksleo** [comment]
安装成功了，但是 yarn run dev 报错
```
[tsl] ERROR in /Users/zacksleo/projects/mpvue-ts/src/pages/sample2/index.ts(7,5)
      TS2345: Argument of type '{ components: { board: VueConstructor<Vue>; }; }' is not assignable to parameter of
 type 'VueClass<Vue>'.
  Object literal may only specify known properties, but 'components' does not exist in type 'VueClass<Vue>'. Did yo
u mean to write 'component'?
```

**Comment by kaven85** [comment]
@zacksleo 同样的问题

**Comment by zacksleo** [comment]
解决不了啊，只能放弃了...

**Comment by tvChan** [comment]
```javascript
@Component
export default class Sample2 extends Vue {
    // 私有属性方式指定data元素
    title: string = '示例页面2';
    content: string = '使用TypeScript+Vue Class组件写法';
    
    components: {
        board
    }
}
```
改成这样就可以~
@zacksleo @kaven85

**Comment by tvChan** [comment]
把`src/types/vue.d.ts`这个文件里面的
`onLaunched();`改成`onLaunched?();`就ok了
@zacksleo @kaven85
